# Generated by Django 4.0.6 on 2022-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.CharField(max_length=60, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='닉네임')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='포인트')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'User',
            },
        ),
    ]
