# Generated by Django 4.0.6 on 2022-11-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='n_changed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='닉네임 변경일'),
        ),
    ]
