# Generated by Django 4.0.6 on 2022-11-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images/%Y/%m/%d/', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=8, unique=True, verbose_name='닉네임'),
        ),
    ]
