# Generated by Django 4.0.6 on 2022-10-28 19:50

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=32, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=8, unique=True, validators=[django.contrib.auth.password_validation.name_validate], verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=20, unique=True, validators=[django.contrib.auth.password_validation.id_validate], verbose_name='아이디'),
        ),
    ]
