# Generated by Django 4.1.3 on 2022-11-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="n_changed",
            field=models.DateTimeField(null=True, verbose_name="닉네임 변경일"),
        ),
    ]
