# Generated by Django 4.1.3 on 2022-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_n_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default="소셜@l57+<", max_length=8, unique=True, verbose_name="닉네임"
            ),
        ),
    ]
