# Generated by Django 4.1.3 on 2022-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=8, unique=True, verbose_name="닉네임"),
        ),
    ]
