# Generated by Django 4.1.3 on 2022-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default="소셜ONPwxZ", max_length=8, unique=True, verbose_name="닉네임"
            ),
        ),
    ]
