# Generated by Django 4.0.6 on 2022-08-19 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='like_user',
            field=models.ManyToManyField(blank=True, related_name='like_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(choices=[('자유', '자유'), ('정보', '정보')], max_length=32, verbose_name='분류'),
        ),
    ]
