# Generated by Django 4.0.6 on 2022-10-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Event',
        ),
    ]
