# Generated by Django 4.0.6 on 2022-10-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_event_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
    ]
