# Generated by Django 4.0.6 on 2022-09-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date'], 'verbose_name': '공지', 'verbose_name_plural': '공지'},
        ),
        migrations.AlterModelTable(
            name='notice',
            table='Notice',
        ),
    ]
