# Generated by Django 4.0.6 on 2022-09-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='name',
        ),
    ]
